
- name: Disable interactive
  shell: export DEBIAN_FRONTEND=noninteractive && dpkg --configure -a

- name: Install common packages
  apt: pkg={{ item }} state=latest update_cache=yes
  with_flattened:
    - "{{common_libs}}"
    - "{{env_libs}}"

- name: Configuring locale to server
  copy: src=locale
        dest=/etc/default/locale
        backup=yes

- name: Configuring locale for bash
  shell: export LC_ALL=en_US.UTF-8 LC_CTYPE=en_US.UTF-8  LC_MESSAGES=POSIX LANGUAGE=en_US.UTF-8

- name: Set timezone to Etc/UTC
  timezone:
    name: Etc/UTC

- name: Configure ntp
  copy: src=ntp.conf dest=/etc/ntp.conf
  become: yes

- name: Restart ntp
  service: name=ntp state=restarted enabled=yes

- name: Add Goolge DNS to resolve.conf
  lineinfile:
    dest: /etc/resolv.conf
    line: "{{item}}"
  with_items:
    - "nameserver 8.8.4.4"
    - "nameserver 8.8.8.8"
    - "nameserver 2001:4860:4860::8888"
    - "nameserver 2001:4860:4860::8844"

- name: Install boto
  shell: "pip install {{item}} -U"
  with_items:
    - boto
    - boto3
    - botocore
    - python-dateutil
  when: env == "dev"

- name: Stop Apache
  service: name=apache2 state=stopped enabled=no
  ignore_errors: yes

- name: Remove Apache
  apt: pkg={{ item }} state=absent
  with_items:
      - apache2

- name: Create "{{base_path}}" directory
  file: path="{{base_path}}" state=directory

