---
- name: Install pghero
  become: yes
  shell: |
      wget -qO- https://dl.packager.io/srv/pghero/pghero/key | sudo apt-key add -
      wget -O /etc/apt/sources.list.d/pghero.list \
        https://dl.packager.io/srv/pghero/pghero/master/installer/ubuntu/18.04.repo
      apt-get update
      apt-get -y install pghero
      pghero config:set DATABASE_URL=postgres://postgres@localhost:5432/postgres
      pghero config:set PORT=3441
      pghero scale web=1






