
base_path: /var/www/application
build_number: ""
common_libs:
    - curl
    - wget
    - build-essential
    - software-properties-common
    - ntp
    - vim
    - screen
    - python-pip
    - apt-transport-https
    - htop
    - aptitude


ssh_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDQy4jChHH/5p7CwO4lr5b6aa33ey3RiUZ6i6aV2bMb88rGl9V3Qu3d3PINlPCfhQ3rje53/k2RT/kf7Jo8BbAqQVmhWmnqwuUclIlRfBWKkg93cChf4NheC3JTr9ycebpKUPGWgka89aL+BRraOHXNh5kQ4EGuYZGLhQI8EJbYNvlQXZYp41gTxli4+/amIbdThY3CX7KhhrHUKcIlxQPOyPIEpfCg+DPGVR86U6U7QU2xNKbf84QD5GVjtUw3KHeygEEJ8lHBIHN3pcVlJIln6Ac7PR9ltLuu681SU5FwvKURKrotAS8D1WlYkREVueeSJ0xcVgN7WWcG/JU+WKmDcb6FWhbsFBSxxQ4s3VX9pCCRq47FyyFs0dVekJXxk0dtDH73D7dNsawykdFFR15aMjvP0OBF8NkQl7UkbxPXnGCPBu/Y51uBZYyn29k124edY4YZu2bU7JqG8ve0K4THtp3RotXxT/cZ9SFPZ94b5yDEkkj0hNK4yhPtUYdnEYLYpw+BXsr7t4qFfiGRZykmnRW/Q/puTzWQ3XCtq15zbtrShYSO/IYkSV8zs+KuGKN7aKxcxpdpVuP1Twq3rlhD34kVtKOlax9iCXkzsFPL+SbQA6Bt9ZjWu2tEwdQUYnzasGa6fFloMX9id/nLEqjo2z2GuL/u1V+w+29DRj3IfQ== you@example.com"

####solr
java_packages:
  - openjdk-8-jdk
solr_version: "7.3.0"
solr_install_path: /opt/solr
solr_home: /var/solr
solr_cores: []
solr_restart_handler_enabled: false
solr_xms: "200M"
solr_xmx: "250M"

s3_artifacts: "{{app_name}}.artifacts"
latest_deploy_build_file: "lastest_{{app_name}}_build"

handlers_enabled: true

enable_php_fpm: yes

mailhog_binary_url: https://github.com/mailhog/MailHog/releases/download/v1.0.0/MailHog_linux_amd64

ulimit_value: 1048576
