---
- name: apt update
  apt: update_cache=yes

- name: Install NodeJS repo
  shell: curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -

- name: Install NodeJs
  apt: pkg={{ item }} state=latest update_cache=yes
  with_items:
    - nodejs

- name: Upgrading npm
  npm: name=npm global=yes state=latest
