
- name: Configure Postgresql
  copy: src="{{item}}"
        dest=/etc/postgresql/10/main/postgresql.conf
        backup=yes
  with_items:
    - postgresql.conf
    - pg_hba.conf


- name: Start Postgres
  service: name=postgresql state=restarted enabled=yes

