---


- name: install aws-cli
  pip:
    name: awscli
    state: latest

- name: install aws-cli
  shell: mkdir -p /root/.aws

- name: configure aws-cli config for root
  template:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
  with_items:
      - { src: credentials.j2 , dest: /root/.aws/credentials }
      - { src: config.j2 , dest: /root/.aws/config }

