


- name: Start postgres instance
  ec2:
     keypair:  "{{ key_name }}"
     group: "general_{{env}}"
     instance_type: "{{ postgres_instance_type }}"
     region: "{{ aws_region }}"
     zone: "{{ item.1 }}"
     image: "{{ image_id }}"
     wait: true
     exact_count: "{{ postgres_count }}"
     count_tag:
        Name: "postgres1_{{env}}"
     instance_tags:
        Group: "postgres1_{{env}}"
        Name: "postgres1_{{env}}"
        Env: "{{env}}"
        Release: "{{release}}"
        Count: "postgres1_{{env}}_count_{{ item.0 + 1 }}"
        CountIndex: "{{ item.0 + 1 }}"
     volumes:
         - device_name: /dev/sda1
           volume_type: gp2
           volume_size: "{{postgres_size}}"
           delete_on_termination: true
  register: postgress
  with_indexed_items: "{{aws_zones}}"

- name: Wait for SSH to come up
  wait_for: host="{{item.public_ip}}" port=22 delay=10 timeout=640 state=started
  with_items: "{{ postgress.results[0].tagged_instances }}"
  when: groups['tag_Name_postgres1_'+env] is not defined

- name: Add host to known_hosts
  shell: mkdir -p ~/.ssh && touch ~/.ssh/known_hosts && ssh-keygen -R {{item.public_ip}} && ssh-keyscan  -t rsa {{item.public_ip}}  >> ~/.ssh/known_hosts
  with_items: "{{ postgress.results[0].tagged_instances }}"
  when: groups['tag_Name_postgres1_'+env] is not defined

- name: Add instance public IP to launched groupname
  add_host:
     name: "{{item.public_ip}}"
     hostname: "{{item.public_ip}}"
     groups: "tag_Name_postgres1_{{env}}"
     ec2_id: "{{ item.id }}"
     ec2_tag_Name: "postgres1_{{env}}"
     ec2_tag_Env: "{{env}}"
     ec2_tag_Count: "postgres1_{{env}}_count_1"
     ec2_tag_CountIndex: "1"
     ec2_tag_Release: "{{release}}"
  with_items: "{{postgress.results[0].tagged_instances}}"
  when: groups['tag_Name_postgres1_'+env] is not defined
