

- name: Get AMI id
  ec2_ami_facts:
    region: "{{ aws_region }}"
    owners: self
    filters:
      name:  "ubuntu18"
  delegate_to: 127.0.0.1
  register: ami_find

- name: Start a set of redis instances
  ec2:
     keypair:  "{{ key_name }}"
     group: "general_{{env}}"
     instance_type: "{{ redis_instance_type }}"
     region: "{{ aws_region }}"
     zone: "{{ item.1 }}"
     image: "{{ image_id }}"
     wait: true
     exact_count: "{{ redis_count }}"
     count_tag:
        Name: "redis1_{{env}}"
     instance_tags:
        Group: "redis1_{{env}}"
        Name: "redis1_{{env}}"
        Env: "{{env}}"
        Release: "{{release}}"
        Count: "redis1_{{env}}_count_{{ item.0 + 1 }}"
        CountIndex: "{{ item.0 + 1 }}"
  register: rediss
  with_indexed_items: "{{aws_zones}}"

- name: Wait for SSH to come up
  wait_for: host="{{item.public_ip}}" port=22 delay=10 timeout=640 state=started
  with_items: "{{ rediss.results[0].tagged_instances }}"
  when: groups['tag_Name_redis1_'+env] is not defined

- name: Add host to known_hosts
  shell: mkdir -p ~/.ssh && touch ~/.ssh/known_hosts && ssh-keygen -R {{item.public_ip}} && ssh-keyscan  -t rsa {{item.public_ip}}  >> ~/.ssh/known_hosts
  with_items: "{{ rediss.results[0].tagged_instances }}"
  when: groups['tag_Name_redis1_'+env] is not defined

- name: Add instance public IP to launched groupname
  add_host:
     name: "{{item.public_ip}}"
     hostname: "{{item.public_ip}}"
     groups: "tag_Name_redis1_{{env}}"
     ec2_id: "{{ item.id }}"
     ec2_tag_Name: "redis1_{{env}}"
     ec2_tag_Env: "{{env}}"
     ec2_tag_Count: "redis1_{{env}}_count_1"
     ec2_tag_CountIndex: "1"
     ec2_tag_Release: "{{release}}"
  with_items: "{{rediss.results[0].tagged_instances}}"
  when: groups['tag_Name_redis1_'+env] is not defined
